# jump-cd PowerShell integration. Generated by "jcd init powershell". Do not edit.
#
# Two hard rules:
#   1. A child process cannot change the parent shell's cwd, so Set-Location
#      must happen in the function below; the binary only prints a path.
#   2. The hot path must not spawn a process. Add-Content is a cmdlet, so
#      recording a visit costs nothing.
#
# ASCII-only on purpose: Windows PowerShell 5.1 decodes an external command's
# output using the console code page, so non-ASCII comments can be mis-decoded
# into characters that break parsing. There is a test for it.
#
# [char]9 is a tab, spelled that way to avoid a backtick escape in the source.

# Resolve the binary once, as an *Application*. Two reasons this is done here
# and not inline:
#   - filtering by Application type keeps "jcd" from resolving to the function
#     below and calling itself forever;
#   - the executable name is platform-dependent ("jcd.exe" on Windows, "jcd"
#     elsewhere), so hardcoding it would break every non-Windows host.
$__jcd_cmd = Get-Command jcd -CommandType Application -ErrorAction SilentlyContinue |
             Select-Object -First 1
$Global:__jcd_bin = $null
if ($__jcd_cmd) { $Global:__jcd_bin = $__jcd_cmd.Source }
if (-not $Global:__jcd_bin) {
    if ($env:OS -eq 'Windows_NT') { $Global:__jcd_bin = 'jcd.exe' } else { $Global:__jcd_bin = 'jcd' }
}

$Global:__jcd_journal = '__JCD_JOURNAL__'

function global:__jcd_hook {
    if (-not $Global:__jcd_journal) { return }
    try {
        $ts = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
        Add-Content -LiteralPath $Global:__jcd_journal -Value ($ts.ToString() + [char]9 + $PWD.Path) -ErrorAction SilentlyContinue
    } catch {
    }
}

if (-not $Global:__jcd_original_prompt) {
    $Global:__jcd_original_prompt = $function:prompt
}

function global:prompt {
    __jcd_hook
    if ($Global:__jcd_original_prompt) {
        & $Global:__jcd_original_prompt
    } else {
        "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
    }
}

function global:jcd {
    # Subcommands are forwarded to the binary; anything else is a jump query.
    $reserved = @('add', 'init', 'query', 'list', 'version', 'help', 'doctor',
                  '--help', '-h', '--version', '-V')
    if ($args.Count -gt 0) {
        $first = [string]$args[0]
        if (($reserved -contains $first) -or $first.StartsWith('__')) {
            & $Global:__jcd_bin @args
            return
        }
    }
    $target = & $Global:__jcd_bin query @args
    if ($LASTEXITCODE -ne 0 -or -not $target) {
        return
    }
    Set-Location -LiteralPath $target
}
