# jump-cd PowerShell integration. Generated by "jcd init powershell". Do not edit.
#
# Two hard rules:
#   1. A child process cannot change the parent shell's cwd, so Set-Location
#      must happen in the function below; the binary only prints a path.
#   2. The hot path must not spawn a process. Add-Content is a cmdlet, so
#      recording a visit costs nothing.
#
# This file is deliberately ASCII-only. Windows PowerShell 5.1 decodes an
# external command's output using the console code page, so non-ASCII comments
# can be mis-decoded into characters that break parsing. There is a test for it.
#
# [char]9 is a tab, spelled that way to avoid a backtick escape in the source.

$Global:__jcd_journal = '__JCD_JOURNAL__'

function global:__jcd_hook {
    if (-not $Global:__jcd_journal) { return }
    try {
        $ts = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
        Add-Content -LiteralPath $Global:__jcd_journal -Value ($ts.ToString() + [char]9 + $PWD.Path) -ErrorAction SilentlyContinue
    } catch {
    }
}

if (-not $Global:__jcd_original_prompt) {
    $Global:__jcd_original_prompt = $function:prompt
}

function global:prompt {
    __jcd_hook
    if ($Global:__jcd_original_prompt) {
        & $Global:__jcd_original_prompt
    } else {
        "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
    }
}

function global:jcd {
    # Subcommands are forwarded to the binary; anything else is a jump query.
    # "jcd.exe" must be spelled with the extension, or this recurses into itself.
    $reserved = @('add', 'init', 'query', 'list', 'version', 'help', 'doctor',
                  '--help', '-h', '--version', '-V')
    if ($args.Count -gt 0) {
        $first = [string]$args[0]
        if (($reserved -contains $first) -or $first.StartsWith('__')) {
            & jcd.exe @args
            return
        }
    }
    # "-" means the previous directory; the binary reads OLDPWD, which
    # PowerShell does not set, so fall back to a jump query.
    $target = & jcd.exe query @args
    if ($LASTEXITCODE -ne 0 -or -not $target) {
        return
    }
    Set-Location -LiteralPath $target
}
